--- #YAML:1.0
name: haver-common
version: 0.05
license: gpl
distribution_type: module
requires:
  POE: 0.27
  perl: 5.6.1
recommends:
  Haver::Client: 0.05
  Haver::Server: 0.05
build_requires: {}
conflicts: {}
provides:
  Haver:
    file: lib/Haver.pm
    version: 0.05
  Haver::Base:
    file: lib/Haver/Base.pm
    version: 0.01
  Haver::Config:
    file: lib/Haver/Config.pm
    version: 0.02
  Haver::Preprocessor:
    file: lib/Haver/Preprocessor.pm
  Haver::Protocol:
    file: lib/Haver/Protocol.pm
    version: 0.03
  Haver::Protocol::Filter:
    file: lib/Haver/Protocol/Filter.pm
    version: 0.02
  Haver::Reload:
    file: lib/Haver/Reload.pm
    version: 0.01
  Haver::Singleton:
    file: lib/Haver/Singleton.pm
    version: 0.03
  Haver::Utils::Logger:
    file: lib/Haver/Utils/Logger.pm
generated_by: Module::Build version 0.21
